import mongoose from "mongoose";

const profileSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    required: true,
  },
  firstName: { type: String, default: "" },
  lastName: { type: String, default: "" },
  certificateName: { type: String, default: "" },
  gender: { type: String, default: "" },
  preferredLanguage: { type: String, default: "" },
  teachingLanguage: { type: String, default: "" },
  dob: { type: String, default: "" },
  github: { type: String, default: "" },
  linkedin: { type: String, default: "" },
  codechef: { type: String, default: "" },
  resume: { type: String, default: "" },
  email: { type: String, default: "" },
  whatsappSameAsPhone: { type: Boolean, default: true },
  updatesOnWhatsapp: { type: Boolean, default: true },
  address1: { type: String, default: "" },
  address2: { type: String, default: "" },
  country: { type: String, default: "India" },
  postalCode: { type: String, default: "" },
  state: { type: String, default: "" },
  district: { type: String, default: "" },
  city: { type: String, default: "" },
  codingLevel: { type: String, default: "" },
  hasLaptop: { type: Boolean, default: true },
  technicalSkills: [{ type: String }],
  parentFirstName: { type: String, default: "" },
  parentLastName: { type: String, default: "" },
  parentRelation: { type: String, default: "" },
  lookingForJobs: { type: String, default: "" },
  expectedCTC: { type: String, default: "" },
  preferredLocation: { type: String, default: "" },
  highestEducation: { type: String, default: "" },
  tenthCGPA: { type: String, default: "" },
  interMarking: { type: String, default: "" },
  interPercentage: { type: String, default: "" },
  interCompletionYear: { type: String, default: "" },
  bachelorDegree: { type: String, default: "" },
  degreeStatus: { type: String, default: "" },
  degreeBranch: { type: String, default: "" },
  degreeMarking: { type: String, default: "" },
  degreePercentage: { type: String, default: "" },
  degreeEndYear: { type: String, default: "" },
  degreeStartYear: { type: String, default: "" },
  instituteCountry: { type: String, default: "India" },
  institutePincode: { type: String, default: "" },
  instituteName: { type: String, default: "" },
  instituteDistrict: { type: String, default: "" },
  instituteCity: { type: String, default: "" },
  isFresher: { type: Boolean, default: true },
  yearsOfExperience: { type: String, default: "" },
  lastCompany: { type: String, default: "" },
  jobRole: { type: String, default: "" },
  noticePeriod: { type: String, default: "" },
  course: { type: String, default: "AI/ML" },
  courseType: { type: String, default: "8 months" },
});

export default mongoose.model("Profile", profileSchema);
